USE chat_db;

CREATE TABLE IF NOT EXISTS messages (
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
    room VARCHAR(255) NOT NULL,
    username NVARCHAR(255) NOT NULL,
    message NVARCHAR(1024) NOT NULL
);
