CREATE TABLE IF NOT EXISTS rooms (
    name VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS messages (
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
    room VARCHAR(255) NOT NULL REFERENCES rooms(name),
    username NVARCHAR(255) NOT NULL,
    message NVARCHAR(1024) NOT NULL
);
